language: java

jdk:
  - oraclejdk7
  - oraclejdk8
  - openjdk7
  - openjdk6

install:
  - chmod +x gradlew

script:
  - ./gradlew clean
  - ./gradlew -Ptag=$TRAVIS_TAG build
  - ./gradlew -Ptag=$TRAVIS_TAG shadowJar

notifications:
  email: false
