language: java

jdk:
  - oraclejdk7
  - oraclejdk8
  - openjdk7
  - openjdk6

# build
script:
  - gradle clean
  - gradle build

after_success: 
  - coveralls
  - bash <(curl -s https://codecov.io/bash)

# notification settings
notifications:
    on_failure: change
